### ISSUE TITLE
Ошибка плагина

### ISSUE THREAD

**Issue by Yusipower** [Ecwid/nextjs-ecwid-plugin#1]
code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: tmp-cpa@undefined
npm ERR! Found: next@12.0.4
npm ERR! node_modules/next
npm ERR!   next@"12.0.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer next@"^11.0.1" from @ecwid/nextjs-ecwid-plugin@0.1.1
npm ERR! node_modules/@ecwid/nextjs-ecwid-plugin
npm ERR!   @ecwid/nextjs-ecwid-plugin@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\yusip\AppData\Local\npm-cache\eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:

**Comment by meteor-ec** [comment]
Приветствую! 

Меня зовут Ильнур, я из команды Эквид.

> See C:\Users\yusip\AppData\Local\npm-cache\eresolve-report.txt for a full report.

@Yusipower пришлите пожалуйста мне этот лог на meteor@ecwid.com

Параллельно я еще перепроверю плагин с next@12.0.4

**Comment by meteor-ec** [comment]
Hi!
Just for your information: Compatibility updated to version Next.js 14 in version 0.1.2 of our package

**Comment by Yusipower** [comment]
👍

вс, 28 янв. 2024 г. в 22:51, Ilnur Basyrov ***@***.***>:

**Comment by Rob142857** [comment]
Amazing, thank you.

**Comment by Rob142857** [comment]
Still having trouble getting this to work with next 14.1.0.  Could you provice an example in a page.tsx file that can sit at root/index to start from please?  Can't get the JS to load

**Comment by Rob142857** [comment]
see deployed attempt here rmesolutions.com.au https://github.com/Rob142857/nextjs-one
have invited you to above repo @meteor-ec , any assistance greatly appreciated

**Comment by meteor-ec** [comment]
Hi @Rob142857 !
Sorry for delay. I've create a [PR](https://github.com/Rob142857/nextjs-one/pull/1/files) in your repo with fix. Please look into it.

We will also correct some details in our instructions. 

Regards,

**Comment by Rob142857** [comment]
Much appreciated, thank you
