### ISSUE TITLE
Compatibility for Next.js 13

### ISSUE THREAD

**Issue by thomasjvu** [Ecwid/nextjs-ecwid-plugin#6]
It seems like this plugin expects `next@"^11.0.1"`, but I was wondering if compatibility with Next.js 13 is in the works?

**Comment by jayrexwebriq** [comment]
Hi @thomasjvu, did you get a solution for this issue?

**Comment by Rob142857** [comment]
Hoping these are being looked at.  Would love an updated build.  next.js now at v14x

**Comment by Rob142857** [comment]
@meteor-ec Hi, Any chance you could get the dependencies updated properly from your side? We would all be most grateful.  I have logged a ticket with ecwig.. hope you are still with them

**Comment by meteor-ec** [comment]
Hi there!

Sorry for the long answer. Thanks for your patience!

We have checked the compatibility with Next.js 14 and released a new version of the 0.1.2 package. Everything should work fine.

You can update the package in your projects
`npm update @ecwid/nextjs-ecwid-plugi`

Feel free to send us feedback!

Best regards,
