### ISSUE TITLE
Too narrow produkcts details windows - Button Code

### ISSUE THREAD

**Issue by WebAppsGS** [Ecwid/nextjs-ecwid-plugin#9]
The inserted button to your own page looks good. After clicking, a window with details will appear, which is too narrow. Incorrect window width.

Button Code added to your own NEXTjs application

I noticed that this is partly influenced by the .ec-size .ec-store style classes, but I don't know how I can permanently influence it through my own CSS, is it possible?

![image](https://github.com/Ecwid/nextjs-ecwid-plugin/assets/1780805/b3fb8470-d18f-4ff0-9eea-a237185c5b9a)

Regards, 
Gerard

ps. general great work, thanks!

**Comment by meteor-ec** [comment]
Hi @GeryS,

Thank you for contacting us! We were able to resolve your issue via email. It turned out to be your theme issue. If you have any further questions, please feel free to contact us.

Thank you very much!
